### Consider the below code to answer further questions:
#### import numpy as np
#### list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]
#### array_list = np.array(object = list_)

##### Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

Yes,Python, list is a built-in data type that represents a collection of objects that are ordered and changeable, while array is a module that provides an array object that is more efficient for numerical operations.

In [1]:
list_ = [ '1' , '2' , '3' , '4' , '5' ]
print(type(list_))

<class 'list'>


In [2]:
import numpy as np
array_list = np.array(object = list_)
print(type(array_list))

<class 'numpy.ndarray'>


#### Q2. Write a code to print the data type of each and every element of both the variables list_ and arra_list.

In [3]:
for i in list_:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [4]:
for i in array_list:
    print(type(i))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


#### Q3. Considering the following changes in the variable, array_list:
#### array_list = np.array(object = list_, dtype = int)
#### Will there be any difference in the data type of the elements present in both the variables, list_ and arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.
#### Consider the below code to answer further questions:
#### import numpy as np
#### num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
#### num_array = np.array(object = num_list)

In [5]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list,dtype=int)

In [6]:
for i in num_list:
    print(type(i))

<class 'list'>
<class 'list'>


In [7]:
for i in num_array:
    print(type(i))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


#### Q4. Write a code to find the following characteristics of variable, num_array:
#### (i) shape
#### (ii) size

In [8]:
a2=np.arange(12,dtype=float).reshape(3,4)
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [9]:
print(a2.shape)

(3, 4)


In [10]:
a2.size

12

#### Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.
#### [Hint: The size of the array will be 9 and the shape will be (3,3).]

In [11]:
a3=np.zeros((3,3))
a3

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [12]:
a3.shape

(3, 3)

In [13]:
a3.size

9

#### Q6. Create an identity matrix of shape (5,5) using numpy functions?
#### [Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [14]:
a4=np.identity(5)
a4

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [15]:
a4.size

25

In [16]:
a4.shape

(5, 5)